var killego = [
  'We must begin by seeing ourselves and the world in a new way for the first time.',
  'First principle is that you must not fool yourself, and you are the easiest perosn to fool',
  'Your worst enemy already lives inside you: your EGO.',
  'Practice self-control',
  'The only relationship between work and chatter is that one kills the other.',
  'It\'s about the doing, not the recognition.',
  'Detachment is a sort of natural ego antidote.',
  'Become a student',
  'A student is like a sponge, absorbing what goes on around him, filtering it, latching on what he can hold',
  'A real student is also his own teacher and his own critic. There is no room for ego there',
  'The art of taking feedback is such a crucial skill in life, particularly harsh and critical feedback',
  'Ego is the Enemy',
  'Greatness comes from humble beginnings',
  'Say little, do much',
  'You cannot lose temper as a refuge form despair',
  'There will be slight dismissals, little fuck yous, one sided compromises, getting yelled. This will make you want to say: I am better than this. I deserve more. YOU MUST DO NOTHING. ENDURE IT. QUIETLY BRUSH IT OFF. WORK HARDER. PLAY THE GAME.',
  'Ignore the noise, do not let it distract you.',
  'A person who thinks all the time has nothing to think except thoughts, so he loses touch with reality and lives in a world of illusions.',
  'The first product of self-knowledge is humility',
  'WORK, WORK, WORK',
  'Don\'t boast. There\'s nothing in it for you',
  'DO YOU REALLY UNDERSTAND? Do you have any idea just how much work there is going to be? Not work until you get your big break, not work until you make a name for yourself, but work, work, WORK, forever and EVER.',
  'Sobriety, open-mindedness, organization, and purpose--  these are the great stabilizers.',
  'No matter what you have done up to this point, you better be a student.',
  'If you are not learning, you are already dying.',
  'Learn from everyone and everything.',
  'Find out why you are after and what you are after.',
  'Ignore those who mess with your pace',
  'Do not be deceived by recognition you have gotten or the amount of moeny in your bank account',
  'Most successful people are people you have never heard of',
  'Courage for instance, lies between cowardice on one end and recklessnes on the other',
  'Failure and adveristy are relative and unique to each of us',
  'Doing the work is enough',
  'If you shut up truth and bury it under the ground, it will but gorw and gather itself such explosive power that the day it bursts through it will blow up everything in its way',
  'Success is a peace of mind which is a direct result of self-satisfaction in knowing you made the effort to do your best to become the best that you are capable of becoming.',
  'The bigger the ego, the harder the fall',
  'Paradox of hate and bitterness: it accomplishes almost exactly the oppposite of what we hope it does',
  'Are we going to be miserable just because other people are',
  'The obsession with the past, with something that someone did or how things should have been, as much as it hurts, is ego emobodied.',
  'See much, study much, suffer much, that is the path to wisodm.',
  'Every day for the rest of your life you will find yourself at one of three phases: aspiration, success, failure. You will battle ego in each of them.',
  'You must sweep the floor every minute of evey day. And then sweep again.'
];

module.exports = function () {
  return killego[Math.floor(Math.random() * killego.length)];
};

module.exports.killego = killego;
